### ISSUE TITLE
无法触发，建议增加一个确认按钮

### ISSUE THREAD

**Issue by YowaiCoder** [ustc-zzzz/YiGeDingLia#12]
机型：魅族16th
系统：Flyme (Android 8.1)
浏览器：Chrome 75
输入法：百度输入法华为版v8.2.6

**Comment by ustc-zzzz** [comment]
请描述复现过程。

**Comment by YowaiCoder** [comment]
就是输入成语没有反应，也没看到有查询按钮触发

**Comment by YowaiCoder** [comment]
是不是在onchange里触发的逻辑，但是以上环境下不能触发onchange？没有电脑不能确认。
