### ISSUE TITLE
添加到“救过不给“和“口谐辞给”的接龙列表

### ISSUE THREAD

**Issue by hentaiplane** [ustc-zzzz/YiGeDingLia#4]

**Comment by ustc-zzzz** [comment]
词库里没有读音“gei”开头的词，在找到更好的词库前不予修复。

**Comment by hentaiplane** [comment]
> 词库里没有读音“gei”开头的词，在找到更好的词库前不予修复。

是啊，我是说像“一个顶俩”一样  可以做个类似的接龙到“救过不给”

**Comment by ouuan** [comment]
可以使用 https://ouuan.github.io/antiyigedinglia/
