### ISSUE TITLE
“万里挑一”无法接到“一个顶俩”

### ISSUE THREAD

**Issue by MCUmbrella** [ustc-zzzz/YiGeDingLia#42]
“万里挑一”测试：
![图片](https://user-images.githubusercontent.com/40854260/131674110-cf707aa5-e921-4514-8a44-3a765273ca72.png)
“九九归一”测试：
![图片](https://user-images.githubusercontent.com/40854260/131674012-d0c325c3-c404-4e34-bf89-a093d0d35e47.png)
“idiom.json”中的搜索结果：
![图片](https://user-images.githubusercontent.com/40854260/131674420-f956d396-b5b5-45ea-b1f1-41f95520fa88.png)
从这个情况来看应该是库里没有“万里挑一”这个成语<br>
*本来是路过的想测试一下凑个热闹 结果上来就直接给人家整不会了（*

**Comment by ustc-zzzz** [comment]
请去 https://github.com/pwxcoo/chinese-xinhua 反馈该问题。
