### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by MasterOfStar** [ustc-zzzz/YiGeDingLia#7]
![Screenshot_2019-08-09-18-13-55-474.png](https://i.loli.net/2019/08/09/9DXvasWrA34tuSC.png)
![Screenshot_2019-08-09-18-14-20-973.png](https://i.loli.net/2019/08/09/h7ZosMyrC6VY5Hv.png)

**Comment by ustc-zzzz** [comment]
都属于无法接上时的报错，而且都来源于手机。请问楼主使用的浏览器是？

**Comment by SeraphJACK** [comment]
两个在 Google Chrome
```
Google Chrome | 76.0.3809.87 (正式版本) （64 位）
修订版本 | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
操作系统 | Linux
JavaScript | V8 7.6.303.27
用户代理 | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
```

上都无法复现。
